version: "3.4"
volumes:
  shared-volume:
services:
  etcd:
    container_name: "etcd"
    image: bitnami/etcd:3
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
    ports:
      - "2379:2379"
      - "2380:2380"
  swoole:
    container_name: "swoole"
    environment:
      IMI_ETCD_HOST: 127.0.0.1
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
