version: "3.4"
volumes:
  shared-volume:
services:
  etcd:
    container_name: "etcd"
    image: bitnami/etcd:${ETCD_VERSION}
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ALLOW_NONE_AUTHENTICATION=yes"
    ports:
      - "2379:2379"
      - "2380:2380"
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET 'http://127.0.0.1:2379/health' | grep '{'" ]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 5s
  swoole:
    container_name: "swoole"
    environment:
      IMI_ETCD_HOST: ${IMI_ETCD_HOST}
      IMI_ETCD_VERSION: ${IMI_ETCD_VERSION}
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
