version: "3.4"
volumes:
  shared-volume:
services:
  etcd:
    container_name: "etcd"
    image: bitnami/etcd:3
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://127.0.0.1:2379"
      #参数指不用密码可以连接
      - "ALLOW_NONE_AUTHENTICATION=yes"
    ports:
      - "2379:2379"
      - "2380:2380"
  swoole:
    container_name: "swoole"
    environment:
      IMI_ETCD_HOST: 127.0.0.1
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: 4.8
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null
